### ISSUE TITLE
easyScripting can't find

### ISSUE THREAD

**Issue by AiWei123** [manuSrep/DisneyDispPy#1]
it's happy sharing the file,but use python to install files,we can't find  easyScripting,can you give me a reply

**Comment by manuSrep** [comment]
easyScripting is now called miscpy. I'll update the code within the next days.

**Comment by AiWei123** [comment]
ok,thank you.I have an another question,now I have installed the DisneyDispPy successfully,when I run the disparity.py,it occurred to me that "the following arguments are required: lightfield",do I need to install something else?thanks for your reply

**Comment by AiWei123** [comment]
I have an another questions,the dataset need to be downloaded at https://www.disneyresearch.com/project/lightfields/,is it true?

**Comment by manuSrep** [comment]
The code is up to date again. There is nothing more to install. "lightfiled" is the argument for the input data. Please see the help entries.
